# Generated by Django 4.2.6 on 2024-01-18 14:07

import colorfield.fields
import datetime
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import polatFashionApp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0018_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori adı")),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategori",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "colorStock",
                    models.PositiveIntegerField(verbose_name="Renk stoklerı"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="",
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="Ana ürün resmi",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        default="",
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="Ürün resmi",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        default="",
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="Ürün resmi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Renk Bilgileri",
                "verbose_name_plural": "Ürün Renk Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="İndirim kodu",
                    ),
                ),
                (
                    "discount_price",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="indirim tutarı"
                    ),
                ),
                (
                    "discount_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 1, 18, 14, 7, 36, 12048, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Bitiş tarihi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim Kodu",
                "verbose_name_plural": "İndirim Kodu",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Ürün miktarı")),
                (
                    "orderDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Sipariş tarihi"
                    ),
                ),
                ("state", models.CharField(max_length=50, verbose_name="Durum")),
                (
                    "change",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="İade/Değişim"
                    ),
                ),
                ("statement", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "change_state",
                    models.CharField(
                        blank=True,
                        default="Değerlendiriliyor",
                        max_length=500,
                        verbose_name="Değişim Durumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş Bilgileri",
                "verbose_name_plural": "Sipariş Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.CharField(max_length=500, verbose_name="Ürün başlığı")),
                ("explanation", models.TextField(verbose_name="Ürün açıklması")),
                (
                    "productColor",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fiyat"
                    ),
                ),
                ("totalStock", models.PositiveIntegerField(verbose_name="Toplam Stok")),
                (
                    "image",
                    models.ImageField(
                        default="",
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="Ana ürün resmi",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        default="",
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="Ürün resmi",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        default="",
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="Ürün resmi",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "man"), ("K", "woman"), ("U", "unisex")],
                        max_length=300,
                        null=True,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "pattern_info",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Kalıp bilgisi",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Materyal"
                    ),
                ),
                (
                    "model_size",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Manken ölçüsü",
                    ),
                ),
                (
                    "body_size",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Model bedeni",
                    ),
                ),
                (
                    "special",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Özel koleksiyon",
                    ),
                ),
                (
                    "color",
                    models.ManyToManyField(
                        blank=True,
                        to="polatFashionApp.color",
                        verbose_name="Ürün renkleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Bilgileri",
                "verbose_name_plural": "Ürün Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="ProductLowerSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size24",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="24"
                    ),
                ),
                (
                    "size26",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="26"
                    ),
                ),
                (
                    "size28",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="28"
                    ),
                ),
                (
                    "size30",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="30"
                    ),
                ),
                (
                    "size32",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="32"
                    ),
                ),
                (
                    "size34",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="34"
                    ),
                ),
                (
                    "size36",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="36"
                    ),
                ),
                (
                    "size38",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="38"
                    ),
                ),
                (
                    "size40",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="40"
                    ),
                ),
                (
                    "size42",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="42"
                    ),
                ),
            ],
            options={
                "verbose_name": "Alt Beden Bilgileri",
                "verbose_name_plural": "Alt Beden Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="ProductTopSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "XS",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="XS"
                    ),
                ),
                (
                    "S",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="S"
                    ),
                ),
                (
                    "M",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="M"
                    ),
                ),
                (
                    "L",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="L"
                    ),
                ),
                (
                    "XL",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="XL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Üst Beden Bilgileri",
                "verbose_name_plural": "Üst Beden Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="SocialMedialGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="sosyal medya resmi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sosyal medya galeri",
                "verbose_name_plural": "Sosyal medya galeri",
            },
        ),
        migrations.CreateModel(
            name="TopBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=polatFashionApp.models.upload_to,
                        verbose_name="banner resmi",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Banner yazısı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banner",
            },
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orderNumber",
                    models.PositiveIntegerField(verbose_name="Sipariş sayısı"),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı İstatistikleri",
                "verbose_name_plural": "Kullanıcı İstatistikleri",
            },
        ),
        migrations.CreateModel(
            name="UserCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        blank=True, default=1, verbose_name="Sipariş sayısı"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, default=1, verbose_name="Sepetteki ürün tutarı"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Sipariş Bedeni"
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polatFashionApp.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Sepeti",
                "verbose_name_plural": "Kullanıcı Sepetleri",
            },
        ),
        migrations.CreateModel(
            name="UsedDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polatFashionApp.discount",
                        verbose_name="Kullanılan indirim Kod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanılmış İndirim Kodu",
                "verbose_name_plural": "Kullanılmış İndirim Kodu",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotion",
                    models.PositiveIntegerField(verbose_name="İndirim miktarı"),
                ),
                (
                    "totalProduct",
                    models.BooleanField(verbose_name="Tüm ürünlerde indirim"),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        to="polatFashionApp.category",
                        verbose_name="Kategoriye göre indirm",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim ve Promosyon",
                "verbose_name_plural": "İndirim ve Promosyon",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="productLowerSize",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polatFashionApp.productlowersize",
                verbose_name="Alt Beden",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productTopSize",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polatFashionApp.producttopsize",
                verbose_name="Üst Beden",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ödeme tarihi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ödeme miktarı"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polatFashionApp.orders",
                        verbose_name="Sipariş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme Alanı",
                "verbose_name_plural": "Ödeme Alanı",
            },
        ),
        migrations.AddField(
            model_name="orders",
            name="product",
            field=models.ManyToManyField(
                to="polatFashionApp.product", verbose_name="Ürün"
            ),
        ),
        migrations.CreateModel(
            name="OrderData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_number",
                    models.PositiveIntegerField(verbose_name="Satış Sayısı"),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 1, 18, 14, 7, 36, 12048, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Satış tarihi",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polatFashionApp.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satış Bilgileri",
                "verbose_name_plural": "Satış Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="InventoryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("now_stock", models.PositiveIntegerField(verbose_name="Mevcut stok")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polatFashionApp.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envanter Durumu",
                "verbose_name_plural": "Envanter Durumu",
            },
        ),
        migrations.AddField(
            model_name="color",
            name="productLowerSize",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polatFashionApp.productlowersize",
                verbose_name="Alt Beden",
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="productTopSize",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polatFashionApp.producttopsize",
                verbose_name="Üst Beden",
            ),
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(max_length=100, verbose_name="Takip numarası"),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(verbose_name="Teslimat numarası"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polatFashionApp.orders",
                        verbose_name="Sipariş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kargo Bilgileri",
                "verbose_name_plural": "Kargo Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
    ]
