# Generated by Django 4.2.6 on 2024-01-24 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 7, 4, 59, 729489, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 7, 4, 59, 729489, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
    ]
