# Generated by Django 4.2.6 on 2024-01-28 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0009_alter_discount_discount_date_alter_orderdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 28, 15, 12, 47, 569579, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 28, 15, 12, 47, 569579, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
    ]
