# Generated by Django 4.2.6 on 2024-02-02 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0010_alter_discount_discount_date_alter_orderdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Sepetteki ürün tutarı'),
        ),
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sipariş Bedeni'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 11, 24, 18, 993316, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 11, 24, 18, 993316, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polatFashionApp.product', verbose_name='Ürün'),
        ),
    ]
