# Generated by Django 4.2.6 on 2024-02-07 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0011_orders_price_orders_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 32, 49, 193457, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 32, 49, 193457, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='mesaj başlığı')),
                ('send_message', models.TextField(blank=True, verbose_name='Kullanıcı mesaj içeriği')),
                ('get_message', models.TextField(default='Beklemede', verbose_name='Admin mesaj içeriği')),
                ('message_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Kullanıcı mesajları',
                'verbose_name_plural': 'Kullanıcı mesajları',
            },
        ),
    ]
