# Generated by Django 4.2.6 on 2024-02-08 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0012_alter_discount_discount_date_alter_orderdata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 8, 19, 1, 31266, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 8, 19, 1, 32254, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
    ]
