# Generated by Django 4.2.6 on 2024-02-10 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0014_remove_promotion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Durumu'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 18, 40, 27, 726214, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 18, 40, 27, 726214, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
    ]
