# Generated by Django 4.2.6 on 2024-03-03 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0018_relavantinfo_socialmedialink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True, verbose_name='Kargo fiyatı')),
            ],
            options={
                'verbose_name': 'Kargo fiyatı',
                'verbose_name_plural': 'Kargo fiyatı',
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 3, 15, 33, 27, 892928, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 3, 15, 33, 27, 892928, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
    ]
