# Generated by Django 4.2.6 on 2024-03-18 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0019_cargoprice_alter_discount_discount_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preInfo', models.TextField(blank=True, null=True, verbose_name='Ön bilgilendirme Şartı')),
                ('distanceSellingAgreement', models.TextField(blank=True, null=True, verbose_name='Mesafeli Satış Sözleşmesi')),
            ],
            options={
                'verbose_name': 'Sözleşme şartları',
                'verbose_name_plural': 'Sözleşme şartları',
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 11, 3, 41, 573969, tzinfo=datetime.timezone.utc), verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 11, 3, 41, 573969, tzinfo=datetime.timezone.utc), verbose_name='Satış tarihi'),
        ),
    ]
