# Generated by Django 4.2.6 on 2024-04-28 11:03

from django.db import migrations, models
import django.utils.timezone
import polatFashionApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('polatFashionApp', '0020_contractterms_alter_discount_discount_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=polatFashionApp.models.upload_to, verbose_name='alt banner resmi')),
            ],
            options={
                'verbose_name': 'bottomBanner',
                'verbose_name_plural': 'bottomBanner',
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Satış tarihi'),
        ),
    ]
